<?php

namespace YahtzeeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getGame($id) {
        $query = $this->createQueryBuilder("g")
            ->leftJoin("g.sheets", "s")
            ->leftJoin("s.player", "p")
            ->where("g.id = :id")
            ->setParameter("id", $id)
            ->getQuery();

        return $query->getSingleResult();
    }

    public function getInProgressGames($userId) {
        $query = $this->createQueryBuilder("g")
            ->leftJoin("g.sheets", "s")
            ->leftJoin("s.player", "p")
            ->select("g.id")
            ->where("p.id = :userId")
            ->andWhere("g.status = 1")
            ->setParameter("userId", $userId)
            ->getQuery();

        return $query->getArrayResult();
    }

    public function getNonStartedGames() {
        $query = $this->createQueryBuilder("g")
            ->select("g.id")
            ->where("g.status = 0")
            ->getQuery();

        return $query->getArrayResult();
    }

    public function getClosedGames($userId) {
        $query = $this->createQueryBuilder("g")
            ->leftJoin("g.sheets", "s")
            ->leftJoin("s.player", "p")
            ->select("g.id")
            ->where("g.status = 2")
            ->andWhere("p.id = :userId")
            ->setParameter("userId", $userId)
            ->getQuery();

        return $query->getArrayResult();
    }
}
