# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        UserBundle\Entity\User: sha512

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        frontend:
            entry_point: ucs.security.authentication_entry_point
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                failure_handler: ucs.security.authentication_failure_handler
                success_handler: ucs.security.authentication_success_handler
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                require_previous_session: false
            logout:
                path:       fos_user_security_logout
                target:     /
                success_handler: ucs.security.logout_success_handler
            remember_me:
                key: %secret%
        default:
            anonymous: ~
            provider: main
            context: _security_frontend

    access_control:
        - { path: ^/frontend-api, roles: ROLE_USER }
